# Generated by Django 2.0.7 on 2018-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepcionista', models.CharField(max_length=30)),
                ('remitente', models.CharField(max_length=30)),
                ('destinatario', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_recibido', models.DateField(verbose_name='Fecha Recibida')),
                ('observacion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Entregada')),
            ],
        ),
    ]
