# Generated by Django 2.0.7 on 2018-07-10 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='recepcionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
