# Generated by Django 2.0.7 on 2018-07-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0002_auto_20180710_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_entrega',
            field=models.DateField(null=True, verbose_name='Fecha Entregada'),
        ),
    ]
