# Generated by Django 2.0.7 on 2018-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0004_auto_20180710_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Entregado'),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_recibido',
            field=models.DateField(verbose_name='Fecha Recibido'),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
