# Generated by Django 2.0.7 on 2018-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0005_auto_20180712_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_recibido',
            field=models.DateTimeField(verbose_name='Fecha Recibido'),
        ),
    ]
