# Generated by Django 2.0.7 on 2018-08-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0009_auto_20180809_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajeria',
            options={'permissions': (('ver_mensajeria', 'Puede ver'), ('crear_mensajeria', 'Puede crear'))},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'permissions': (('ver_reporte', 'Puede ver'), ('crear_reporte', 'Puede crear'))},
        ),
    ]
