# Generated by Django 2.0.7 on 2018-08-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0011_mensajeria_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='sucursal',
            field=models.CharField(default='prueba', max_length=30),
            preserve_default=False,
        ),
    ]
