# Generated by Django 2.0.7 on 2018-09-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0012_mensajeria_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajeria',
            options={},
        ),
    ]
