# Generated by Django 2.0.7 on 2018-09-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0013_auto_20180901_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='permiso',
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={},
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
    ]
