# Generated by Django 2.0.7 on 2018-09-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0015_permiso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'permissions': (('ver', 'Puede ver'), ('crear_mensajeria', 'Puede crear mensajeria'), ('crear_reporte', 'Puede crear reporte'), ('eliminar', 'Puede Eliminar'))},
        ),
    ]
