# Generated by Django 2.0.7 on 2018-09-20 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensajeria', '0016_auto_20180901_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria_Externa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30, verbose_name='Codigo de Mensajeria')),
                ('mensajero', models.CharField(max_length=30, verbose_name='Nombre Mensajero')),
                ('fecha_envio_depto', models.DateField(verbose_name='Fecha Enviado Depto.')),
                ('hora_envio_depto', models.TimeField(verbose_name='Hora Enviado Depto.')),
                ('departamento', models.CharField(max_length=30, verbose_name='Nombre de Departamento')),
                ('encargado', models.CharField(max_length=30, verbose_name='Encargado del Departamento')),
                ('entregado_por', models.CharField(max_length=30, verbose_name='Quien Entrega')),
                ('descripcion', models.CharField(max_length=200)),
                ('destinatario', models.CharField(max_length=30)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=5)),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora Salida Mensajero')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora Entrada Mensajero')),
                ('acuse', models.CharField(max_length=200)),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Mensajeria',
            new_name='Mensajeria_Interna',
        ),
    ]
