# Generated by Django 2.0.7 on 2018-09-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0017_auto_20180920_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria_externa',
            name='acuse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
