# Generated by Django 2.0.7 on 2018-10-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0020_auto_20181002_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria_externa',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mensajeria.Departamento'),
        ),
    ]
