# Generated by Django 2.0.7 on 2018-10-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0021_auto_20181002_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria_interna',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
