# Generated by Django 2.0.7 on 2018-11-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0024_mensajeria_interna_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria_interna',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Alta', 'Alta')], max_length=5),
        ),
    ]
