# Generated by Django 2.0.7 on 2018-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0025_auto_20181102_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria_interna',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('Pendiente', 'Pendiente'), ('En Transito', 'En Transito')], max_length=15),
        ),
    ]
