# Generated by Django 2.0.7 on 2018-11-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0026_auto_20181109_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria_interna',
            name='fecha_enviado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Enviado'),
        ),
        migrations.AddField(
            model_name='mensajeria_interna',
            name='fecha_recibido_int',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Recibido en Recp.'),
        ),
        migrations.AlterField(
            model_name='mensajeria_interna',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('Pendiente', 'Pendiente'), ('En Transito', 'En Transito'), ('Retenido', 'Retenido')], max_length=15),
        ),
    ]
