# Generated by Django 2.0.7 on 2018-11-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0027_auto_20181109_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria_interna',
            name='hist_entregado_por',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mensajeria_interna',
            name='hist_enviado_por',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mensajeria_interna',
            name='hist_recibido_por',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
