# Generated by Django 2.0.7 on 2018-11-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0028_auto_20181120_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='vlan',
            field=models.CharField(default='10.20.105', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensajeria_interna',
            name='hist_entregado_por',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Historial Entregado por'),
        ),
        migrations.AlterField(
            model_name='mensajeria_interna',
            name='hist_enviado_por',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Historial Enviado por'),
        ),
        migrations.AlterField(
            model_name='mensajeria_interna',
            name='hist_recibido_por',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Historial Recibido por'),
        ),
    ]
