# Generated by Django 2.0.7 on 2018-11-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0029_auto_20181126_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria_externa',
            name='estado',
            field=models.CharField(choices=[('En Transito', 'En Transito'), ('Enviado', 'Enviado')], default='En Transito', max_length=15),
            preserve_default=False,
        ),
    ]
