# Generated by Django 2.0.7 on 2018-11-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0030_mensajeria_externa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria_externa',
            name='archivo',
            field=models.FileField(default='', upload_to='acuse/'),
            preserve_default=False,
        ),
    ]
