# Generated by Django 2.0.7 on 2018-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0032_auto_20181130_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria_externa',
            name='archivo',
            field=models.FileField(upload_to='acuse/'),
        ),
    ]
