# Generated by Django 2.0.7 on 2018-12-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0035_auto_20181204_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajeria_externa',
            old_name='archivo_acuse',
            new_name='archivo_acuses',
        ),
    ]
