# Generated by Django 2.0.7 on 2019-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0036_auto_20181204_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria_interna',
            name='remitente_externo',
            field=models.BooleanField(default=False),
        ),
    ]
