# Generated by Django 2.0.7 on 2019-01-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0037_mensajeria_interna_remitente_externo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mostrar_chat_de_ayuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_chat_de_ayuda', models.BooleanField(default=False)),
            ],
        ),
    ]
